export const TotalDays = [
{day: "TUE", holiday: false, holidayDetails: "", date: "1-1-2019", week:1},
{day: "WED", holiday: false, holidayDetails: "", date: "2-1-2019",week:1},
{day: "THU", holiday: false, holidayDetails: "", date: "3-1-2019",week:1},
{day: "FRI", holiday: false, holidayDetails: "", date: "4-1-2019",week:1},
{day: "SAT", holiday: false, holidayDetails: "", date: "5-1-2019",week:1},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "6-1-2019",week:2},
{day: "MON", holiday: false, holidayDetails: "", date: "7-1-2019",week:2},
{day: "TUE", holiday: false, holidayDetails: "", date: "8-1-2019",week:2},
{day: "WED", holiday: false, holidayDetails: "", date: "9-1-2019",week:2},
{day: "THU", holiday: false, holidayDetails: "", date: "10-1-2019",week:2},
{day: "FRI", holiday: false, holidayDetails: "", date: "11-1-2019",week:2},
{day: "SAT", holiday: false, holidayDetails: "", date: "12-1-2019",week:2},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "13-1-2019",week:3},
{day: "MON", holiday: false, holidayDetails: "", date: "14-1-2019",week:3},
{day: "TUE", holiday: false, holidayDetails: "", date: "15-1-2019",week:3},
{day: "WED", holiday: false, holidayDetails: "", date: "16-1-2019",week:3},
{day: "THU", holiday: false, holidayDetails: "", date: "17-1-2019",week:3},
{day: "FRI", holiday: false, holidayDetails: "", date: "18-1-2019",week:3},
{day: "SAT", holiday: false, holidayDetails: "", date: "19-1-2019",week:3},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "20-1-2019",week:4},
{day: "MON", holiday: false, holidayDetails: "", date: "21-1-2019",week:4},
{day: "TUE", holiday: false, holidayDetails: "", date: "22-1-2019",week:4},
{day: "WED", holiday: false, holidayDetails: "", date: "23-1-2019",week:4},
{day: "THU", holiday: false, holidayDetails: "", date: "24-1-2019",week:4},
{day: "FRI", holiday: false, holidayDetails: "", date: "25-1-2019",week:4},
{day: "SAT", holiday: false, holidayDetails: "", date: "26-1-2019",week:4},
{day: "SUN", holiday: true, holidayDetails: "weekend holiday", date: "27-1-2019",week:5},
{day: "MON", holiday: false, holidayDetails: "", date: "28-1-2019",week:5},
{day: "TUE", holiday: false, holidayDetails: "", date: "29-1-2019",week:5},
{day: "WED", holiday: false, holidayDetails: "", date: "30-1-2019",week:5},
{day: "THU", holiday: false, holidayDetails: "", date: "1-2-2019",week:1},
{day: "FRI", holiday: false, holidayDetails: "", date: "2-2-2019",week:1},
{day: "SAT", holiday: false, holidayDetails: "", date: "3-2-2019",week:1},
{day: "SUN", holiday: true, holidayDetails: "weekend holiday", date: "4-2-2019",week:2},
{day: "MON", holiday: false, holidayDetails: "", date: "5-2-2019",week:2},
{day: "TUE", holiday: false, holidayDetails: "", date: "6-2-2019",week:2},
{day: "WED", holiday: false, holidayDetails: "", date: "7-2-2019",week:2},
{day: "THU", holiday: false, holidayDetails: "", date: "8-2-2019",week:2},
{day: "FRI", holiday: false, holidayDetails: "", date: "9-2-2019",week:2},
{day: "SAT", holiday: false, holidayDetails: "", date: "10-2-2019",week:2},
{day: "SUN", holiday: true, holidayDetails: "weekend holiday", date: "11-2-2019",week:3},
{day: "MON", holiday: false, holidayDetails: "", date: "12-2-2019",week:3},
{day: "TUE", holiday: false, holidayDetails: "", date: "13-2-2019",week:3},
{day: "WED", holiday: false, holidayDetails: "", date: "14-2-2019",week:3},
{day: "THU", holiday: false, holidayDetails: "", date: "15-2-2019",week:3},
{day: "FRI", holiday: false, holidayDetails: "", date: "16-2-2019",week:3},
{day: "SAT", holiday: false, holidayDetails: "", date: "17-2-2019",week:3},
{day: "SUN", holiday: true, holidayDetails: "weekend holiday", date: "18-2-2019",week:4},
{day: "MON", holiday: false, holidayDetails: "", date: "19-2-2019",week:4},
{day: "TUE", holiday: false, holidayDetails: "", date: "20-2-2019",week:4},
{day: "WED", holiday: false, holidayDetails: "", date: "21-2-2019",week:4},
{day: "THU", holiday: false, holidayDetails: "", date: "22-2-2019",week:4},
{day: "FRI", holiday: false, holidayDetails: "", date: "23-2-2019",week:4},
{day: "SAT", holiday: false, holidayDetails: "", date: "24-2-2019",week:4},
{day: "SUN", holiday: true, holidayDetails: "weekend holiday", date: "25-2-2019",week:5},
{day: "MON", holiday: false, holidayDetails: "", date: "27-2-2019",week:5},
{day: "TUE", holiday: false, holidayDetails: "", date: "28-2-2019",week:5},
{day: "WED", holiday: false, holidayDetails: "", date: "1-3-2019", week:1},
{day: "THU", holiday: false, holidayDetails: "", date: "2-3-2019",week:1},
{day: "FRI", holiday: false, holidayDetails: "", date: "3-3-2019",week:1},
{day: "SAT", holiday: false, holidayDetails: "", date: "4-3-2019",week:1},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "5-3-2019",week:2},
{day: "MON", holiday: false, holidayDetails: "", date: "6-3-2019",week:2},
{day: "TUE", holiday: false, holidayDetails: "", date: "7-3-2019",week:2},
{day: "WED", holiday: false, holidayDetails: "", date: "8-3-2019",week:2},
{day: "THU", holiday: false, holidayDetails: "", date: "9-3-2019",week:2},
{day: "FRI", holiday: false, holidayDetails: "", date: "10-3-2019",week:2},
{day: "SAT", holiday: false, holidayDetails: "", date: "11-3-2019",week:2},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "12-3-2019",week:3},
{day: "MON", holiday: false, holidayDetails: "", date: "13-3-2019",week:3},
{day: "TUE", holiday: false, holidayDetails: "", date: "14-3-2019",week:3},
{day: "WED", holiday: false, holidayDetails: "", date: "15-3-2019",week:3},
{day: "THU", holiday: false, holidayDetails: "", date: "16-3-2019",week:3},
{day: "FRI", holiday: false, holidayDetails: "", date: "17-3-2019",week:3},
{day: "SAT", holiday: false, holidayDetails: "", date: "18-3-2019",week:3},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "19-3-2019",week:4},
{day: "MON", holiday: false, holidayDetails: "", date: "20-3-2019",week:4},
{day: "TUE", holiday: false, holidayDetails: "", date: "21-3-2019",week:4},
{day: "WED", holiday: false, holidayDetails: "", date: "22-3-2019",week:4},
{day: "THU", holiday: false, holidayDetails: "", date: "23-3-2019",week:4},
{day: "FRI", holiday: false, holidayDetails: "", date: "24-3-2019",week:4},
{day: "SAT", holiday: false, holidayDetails: "", date: "25-3-2019",week:4},
{day: "SUN", holiday: true, holidayDetails: "weekend holiday", date: "26-3-2019",week:5},
{day: "MON", holiday: false, holidayDetails: "", date: "27-3-2019",week:5},
{day: "TUE", holiday: false, holidayDetails: "", date: "28-3-2019",week:5},
{day: "WED", holiday: false, holidayDetails: "", date: "29-3-2019",week:5},
{day: "THU", holiday: false, holidayDetails: "", date: "30-3-2019",week:5},
{day: "FRI", holiday: false, holidayDetails: "", date: "31-3-2019",week:5},
{day: "SAT", holiday: false, holidayDetails: "", date: "1-4-2019", week:1},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "2-4-2019",week:2},
{day: "MON", holiday: false, holidayDetails: "", date: "3-4-2019",week:2},
{day: "TUE", holiday: false, holidayDetails: "", date: "4-4-2019",week:2},
{day: "WED", holiday: false, holidayDetails: "", date: "5-4-2019",week:2},
{day: "THU", holiday: true, holidayDetails: "", date: "6-4-2019",week:2},
{day: "FRI", holiday: false, holidayDetails: "", date: "7-4-2019",week:2},
{day: "SAT", holiday: false, holidayDetails: "", date: "8-4-2019",week:2},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "9-4-2019",week:3},
{day: "MON", holiday: false, holidayDetails: "", date: "10-4-2019",week:3},
{day: "TUE", holiday: false, holidayDetails: "", date: "11-4-2019",week:3},
{day: "WED", holiday: false, holidayDetails: "", date: "12-4-2019",week:3},
{day: "THU", holiday: false, holidayDetails: "", date: "13-4-2019",week:3},
{day: "FRI", holiday: false, holidayDetails: "", date: "14-4-2019",week:3},
{day: "SAT", holiday: false, holidayDetails: "", date: "15-4-2019",week:3},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "16-4-2019",week:4},
{day: "MON", holiday: false, holidayDetails: "", date: "17-4-2019",week:4},
{day: "TUE", holiday: false, holidayDetails: "", date: "18-4-2019",week:4},
{day: "WED", holiday: false, holidayDetails: "", date: "19-4-2019",week:4},
{day: "THU", holiday: false, holidayDetails: "", date: "20-4-2019",week:4},
{day: "FRI", holiday: false, holidayDetails: "", date: "21-4-2019",week:4},
{day: "SAT", holiday: false, holidayDetails: "", date: "22-4-2019",week:4},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "23-4-2019",week:5},
{day: "MON", holiday: false, holidayDetails: "", date: "24-4-2019",week:5},
{day: "TUE", holiday: false, holidayDetails: "", date: "25-4-2019",week:5},
{day: "WED", holiday: false, holidayDetails: "", date: "26-4-2019",week:5},
{day: "THU", holiday: false, holidayDetails: "", date: "27-4-2019",week:5},
{day: "FRI", holiday: false, holidayDetails: "", date: "28-4-2019",week:5},
{day: "SAT", holiday: false, holidayDetails: "", date: "29-4-2019",week:5},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "30-4-2019",week:6},
{day: "MON", holiday: false, holidayDetails: "", date: "1-5-2019", week:1},
{day: "TUE", holiday: false, holidayDetails: "", date: "2-5-2019",week:1},
{day: "WED", holiday: false, holidayDetails: "", date: "3-5-2019",week:1},
{day: "THU", holiday: false, holidayDetails: "", date: "4-5-2019",week:1},
{day: "FRI", holiday: false, holidayDetails: "", date: "5-5-2019",week:1},
{day: "SAT", holiday: false, holidayDetails: "", date: "6-5-2019",week:1},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "7-5-2019",week:2},
{day: "MON", holiday: false, holidayDetails: "", date: "8-5-2019",week:2},
{day: "TUE", holiday: false, holidayDetails: "", date: "9-5-2019",week:2},
{day: "WED", holiday: false, holidayDetails: "", date: "10-5-2019",week:2},
{day: "THU", holiday: false, holidayDetails: "", date: "11-5-2019",week:2},
{day: "FRI", holiday: false, holidayDetails: "", date: "12-5-2019",week:2},
{day: "SAT", holiday: false, holidayDetails: "", date: "13-5-2019",week:2},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "14-5-2019",week:3},
{day: "MON", holiday: false, holidayDetails: "", date: "15-5-2019",week:3},
{day: "TUE", holiday: false, holidayDetails: "", date: "16-5-2019",week:3},
{day: "WED", holiday: false, holidayDetails: "", date: "17-5-2019",week:3},
{day: "THU", holiday: false, holidayDetails: "", date: "18-5-2019",week:3},
{day: "FRI", holiday: false, holidayDetails: "", date: "19-5-2019",week:3},
{day: "SAT", holiday: false, holidayDetails: "", date: "20-5-2019",week:3},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "21-5-2019",week:4},
{day: "MON", holiday: false, holidayDetails: "", date: "22-5-2019",week:4},
{day: "TUE", holiday: false, holidayDetails: "", date: "23-5-2019",week:4},
{day: "WED", holiday: false, holidayDetails: "", date: "24-5-2019",week:4},
{day: "THU", holiday: false, holidayDetails: "", date: "25-5-2019",week:4},
{day: "FRI", holiday: false, holidayDetails: "", date: "26-5-2019",week:4},
{day: "SAT", holiday: false, holidayDetails: "", date: "27-5-2019",week:4},
{day: "SUN", holiday: true, holidayDetails: "Weekend holiday", date: "28-5-2019",week:5},
{day: "MON", holiday: false, holidayDetails: "", date: "29-5-2019",week:5},
{day: "TUE", holiday: false, holidayDetails: "", date: "30-5-2019",week:5},
{day: "WED", holiday: false, holidayDetails: "", date: "31-5-2019",week:5},
]